[package]
name = "udp-works"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "shared",
    "tftp-server",
]

[dependencies]
tftp-server = { path = "tftp-server" }
