[package]
name = "dhcp-client"
version = "0.1.0"
edition = "2021"

[lib]
name = "dhcp_client"

[[bin]]
name = "dhcp-client"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = { path = "../shared" }
rand = "0.8"
